### ISSUE TITLE
Swedish radar sehud = sehuv

### ISSUE THREAD

**Issue by nwhpt** [enram/data-repository#107]
The Swedish radar station sehud is currently stated as "Hudriksvall" (with "r") and sehuv as "Hudiksvall". This concerns the same radar site and the correct name is "Hudiksvall". There are currently two separate entries in the archive and also in the visualisation section.

**Comment by CeciliaNilsson709** [comment]
Hi Nadja, thanks for catching the typo in the sitename, indeed they should both be Hudriksvall. 

"sehud" was renamed "sehuv" by SMHI after upgrades in 2016, which is why they have separate entrees in the repository. In this case they are on the same site and could maybe have been merged for our use case, but the repository mirrors the OPERA database where SMHI has decided to keep them separate, with "sehud" for older data and "sehuv" for later data.

**Comment by peterdesmet** [comment]
I have reported the incorrect location name to Marko from OPERA.

I have already manually fixed it at https://aloftdata.eu/radars/#sweden (while working on #103) and at [CROW](https://crow.aloftdata.eu#/?radar=sehud&date=2023-09-20&interval=24&timedisplay=radarLocal&vpiMode=mtr&vpColorScheme=viridis&lang=en).

**Comment by nwhpt** [comment]
The correct name is "Hudiksvall", without r.

**Comment by peterdesmet** [comment]
My bad, now corrected.
